# Generated by Django 4.0.4 on 2022-06-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_rename_number_sale_quantity_sale_client_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.CharField(choices=[('Alex Ernst', 'Alex Ernst')], default='.', max_length=40),
        ),
    ]
