# Generated by Django 4.0.4 on 2022-06-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
