# Generated by Django 4.0.4 on 2022-06-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('supplier', models.CharField(choices=[(' ', ' '), ('Buenimar', 'Buenimar'), ('TiendaMia', 'TiendaMia')], default='', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prod_img/')),
                ('description', models.TextField(blank=True, default=' ', null=True)),
            ],
        ),
    ]
