# Generated by Django 4.0.4 on 2022-06-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='', max_length=40),
        ),
    ]
