# Generated by Django 4.0.4 on 2022-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(choices=[(' ', ' '), ('Buenimar', 'Buenimar'), ('TiendaMia', 'TiendaMia')], default='', max_length=40),
        ),
    ]
