# Generated by Django 4.0.4 on 2022-06-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.CharField(default='.', max_length=40),
        ),
    ]
