# Generated by Django 4.0.4 on 2022-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.CharField(choices=[(' ', ' '), ('Juan Pineda', 'Juan Pineda'), ('Alex Ernst', 'Alex Ernst')], default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[(' ', ' '), ('Hamburguesas', 'Hamburguesas'), ('PC stands', 'PC stands')], default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
