# Generated by Django 4.0.4 on 2022-06-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_date_alter_sale_client_alter_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.CharField(blank=True, default=' ', max_length=40, null=True),
        ),
    ]
